web/InventorySystem/config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :file_tasks do
    member do
      get :manual_update
    end

    collection do
      get :search
    end
  end
  resources :inventory_files
  resources :settings
  resources :parts do
    collection do
      match :import, action: :import, via: [:get, :post]
      get :search
    end
  end

  get 'dashboard/index'

  get 'dashboard/setting'

  post 'dashboard/setting'

  root to: 'dashboard#index'

  resources :inventories do
    collection do
      match :import, action: :import, via: [:get, :post]
      get :search
      get :random
    end
  end

  resources :files do
    collection do
      get :download
    end
  end

  resources :users do
    collection do
      match :import, action: :import, via: [:get, :post]
      get :search
    end
  end

  mount ApplicationAPI => '/api'
end

web/InventorySystem/app/views/shared/_footer.html.erb
<div class="footer">
  <span>© 2016 上海伊弗信息科技有限公司</span>
</div>

web/InventorySystem/app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Inventory System</a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav navbar-right">
				<!--<li><a href="#">Dashboard</a></li>
				<li><a href="#">Settings</a></li>
				<li><a href="#">Profile</a></li>
				<li><a href="#">Help</a></li>-->
			</ul>
		</div>
	</div>
</nav>

web/InventorySystem/app/views/shared/_sidebar.html.erb
<nav class="navbar navbar-default">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Inventory System</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
            <li class=<%= 'active' if 'dashboard'==@current_controller && 'index'==@current_action %>><%= link_to '盘点统计', root_path %></li>
            <li class=<%= 'active' if 'users' ==@current_controller %>><%= link_to '用户管理', users_path %></li>
            <!--<li class=<%= 'active' if 'parts' ==@current_controller %>><%= link_to '零件管理', parts_path %></li>-->
            <li class=<%= 'active' if 'inventories'==@current_controller %>><%= link_to '盘点数据管理', inventories_path %></li>
            <li class=<%= 'active' if 'file_tasks'==@current_controller %>><%= link_to '上传数据列表', file_tasks_path %></li>
            <li class=<%= 'active' if 'settings'==@current_controller %>><%= link_to '系统配置', settings_path %></li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  <!-- /.container-fluid -->
</nav>