web/InventorySystem/config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :file_tasks do
    member do
      get :manual_update
    end

    collection do
      get :search
    end
  end
  resources :inventory_files
  resources :settings
  resources :parts do
    collection do
      match :import, action: :import, via: [:get, :post]
      get :search
    end
  end

  get 'dashboard/index'

  get 'dashboard/setting'

  post 'dashboard/setting'

  root to: 'dashboard#index'

  resources :inventories do
    collection do
      match :import, action: :import, via: [:get, :post]
      get :search
      get :random
    end
  end

  resources :files do
    collection do
      get :download
    end
  end

  resources :users do
    collection do
      match :import, action: :import, via: [:get, :post]
      get :search
    end
  end

  mount ApplicationAPI => '/api'
end

web/InventorySystem/app/models/inventory.rb
# == Schema Information
#
# Table name: inventories
#
#  id                :integer          not null, primary key
#  department        :string(255)      not null
#  position          :string(255)      not null
#  part_nr              :string(255)      not null
#  check_qty         :float(24)
#  check_user        :string(255)
#  check_time        :datetime
#  random_check_qty  :float(24)
#  random_check_user :string(255)
#  random_check_time :datetime
#  is_random_check   :boolean          default(FALSE)
#  ios_created_id    :string(255)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Inventory < ActiveRecord::Base
  PART_TYPES=%w(U L E M)


  validates :sn, :department, :position, :part_nr, :part_unit, presence: true
  validates :part_nr, uniqueness: {scope: [:position, :department], message: '库位+部门+零件 必须唯一'}
  validates :sn, uniqueness: {message: '序列号 必须唯一'}
  validates_inclusion_of :part_type, in: PART_TYPES, message: '零件类型不正确' #, if: Proc.new { |i| i.part_type.present? }

  before_save :set_default_value

  # belongs_to :part, foreign_key: :part_nr, primary_key: :nr

  # scope :check, -> { where("check_qty != '' or check_qty is not null") }
  # scope :random_check, -> { where("is_random_check is true") }
  # scope :random_check_not, -> { where("is_random_check is true and random_check_qty is null") }
  # scope :random_check_completed, -> { where("is_random_check is true and random_check_qty != ''") }
  # scope :position_client, -> { where("ios_created_id != ''") }
  # scope :position_unclient, -> { where("ios_created_id = '' or ios_created_id is null") }

  scope :check, -> { where("check_qty != '' or check_qty is not null") }
  scope :random_check, -> { where("is_random_check is true") }
  scope :random_check_not, -> { where("is_random_check is true and random_check_qty is null") }
  scope :random_check_completed, -> { where("is_random_check is true and random_check_qty is not null") }
  scope :position_client, -> { where("ios_created_id is not null") }
  scope :position_unclient, -> { where("ios_created_id = '' or ios_created_id is null") }

  # def self.full_query
  #   joins(:part).select('parts.unit as part_unit,parts.type as part_type,inventories.*')
  # end

  self.per_page = 50
  default_scope { order('sn asc') }

  def self.search(search)
    if search
      where("part_nr LIKE ?", "%#{search}%")
    else
      find(:all)
    end
  end

  def self.check_for_search(search)
    # puts "======testing"
    where("position=?", search)
  end

  def self.search_by_condition(department, position_begin, position_end, part_nr, ios_created_id, is_random_check, params={})
    inventories = Inventory
    condition = {}
    condition["department"] = department if department.present?
    condition[:check_user]=params[:check_user] if params[:check_user].present?
    condition[:random_check_user]=params[:random_check_user] if params[:random_check_user].present?
    # condition["position"] = position_begin...position_end if position_begin.present? && position_end.present?    
    # condition["ios_created_id"] = ios_created_id if ios_created_id.present?
    condition["is_random_check"] = is_random_check if is_random_check.present?
    # condition["part"] =~ /part/ if part.present?
    inventories = inventories.where(condition)
    inventories = inventories.where("part_nr like '%#{part_nr}%' ") if part_nr.present?
    if ios_created_id.present?
      if ios_created_id == '1'
        inventories = inventories.where("(ios_created_id is not null and ios_created_id!='')")
      else
        inventories = inventories.where("(ios_created_id is null  or ios_created_id='')")
      end
    end
    inventories = inventories.where("(position between '#{position_begin}' and '#{position_end}') or position like '%#{position_begin}%' or position like '%#{position_end}%' ") if position_begin.present? & position_end.present?
    # inventories = inventories.where("position like '%#{position_end}%' ") if position_end.present?
    inventories=inventories.where(sn: params[:sn_begin]..params[:sn_end]) if params[:sn_begin].present? && params[:sn_end].present?
    inventories
  end

  def self.create_random_data
    Inventory.update_all(random_check_qty: nil, random_check_user: nil, random_check_time: nil, is_random_check: false)

    page_size=200

    self.uniq.pluck(:department).each do |deparment|
      ids=[]
      page_index=0
      while true
        ids= self.where(department: deparment).offset(page_size*page_index).limit(page_size).pluck(:id)
        # puts "#{ids}---------"
        sample_count= (ids.count* Setting.random_percent_value).round
        # puts "###############{ids.count}#####{Setting.random_percent_value}#######{sample_count}"
        self.where(id: ids.sample(sample_count)).update_all(is_random_check: true)
        page_index+=1
        break if ids.count==0
      end
    end
  end


  def is_random_check_display
    self.is_random_check ? '是' : '否'
  end

  def check_time_display
    self.check_time.nil? ? nil : self.check_time.strftime("%Y-%m-%d %H:%M:%S")
  end

  def random_check_time_display
    self.random_check_time.nil? ? nil : self.random_check_time.strftime("%Y-%m-%d %H:%M:%S")
  end

  def self.validate_part_type(type)
    PART_TYPES.include?(type)
  end

  def self.generate_file type
    inventories=[]
    case type
      when FileUploadType::OVERALL
        inventories=Inventory.all
      when FileUploadType::SPOTCHECK
        inventories=Inventory.random_check
    end

    Inventory.transaction do
      data=[]
      file=InventoryFile.new()

      inventories.each do |i|
        info={}
        info['id']=i.id.to_s
        info['department']=i.department.to_s
        info['position']=i.position.to_s
        info['part_nr']=i.part_nr.to_s
        info['check_qty']=i.check_qty.to_s

        info['check_user']=i.check_user.to_s
        info['check_time']=i.check_time.to_s
        info['random_check_qty']=i.random_check_qty.to_s
        info['random_check_user']=i.random_check_user.to_s
        info['random_check_time']=i.random_check_time.to_s

        info['is_random_check']=i.is_random_check.to_s
        info['ios_created_id']=i.ios_created_id.to_s
        info['sn']=i.sn.to_s
        info['part_unit']=i.part_unit.to_s
        info['part_type']=i.part_type.to_s

        info['wire_nr']=i.wire_nr.to_s
        info['process_nr']=i.process_nr.to_s

        data<<info
      end

      File.open('uploadfiles/data/data.json', 'w+') do |f|
        f.write(data.to_json.to_s)
        file.path = f
      end

      if file.save
        file
      else
        nil
      end
    end
  end

  private

  def set_default_value
    if self.ios_created_id.blank?
      self.ios_created_id=nil
    end

    if self.check_user.blank?
      self.check_user=nil
    end

    if self.random_check_user.blank?
      self.random_check_user=nil
    end


  end
end

web/InventorySystem/app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]

  def random
    Inventory.create_random_data
    respond_to do |format|
      format.js
    end

  end

  def import
    if request.post?
      msg = Message.new
      tmp_file_path = 'uploadfiles'

      begin
        file = params[:files][0]
        fd = FileData.new(data: file, oriName: file.original_filename, path: tmp_file_path, pathName: "#{Time.now.strftime('%Y%m%d%H%M%S%L')}~#{file.original_filename}")
        fd.save
        msg = Excel::InventoryService.import(fd)
      rescue => e
        msg.content = e.message
      end
      render json: msg
    end
  end

  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory

    if params[:search]
      puts "-----testing "
      # @inventories = @inventories.search(params[:search])
      @department = params[:department]
      @check_user=params[:check_user]
      @position_begin = params[:position_begin]
      @position_end = params[:position_end]
      @part_nr = params[:part_nr]
      @ios_created_id = params[:ios_created_id]
      @is_random_check = params[:is_random_check]
      @inventories = Inventory.search_by_condition(@department, @position_begin, @position_end, @part_nr, @ios_created_id, @is_random_check, {check_user: @check_user,
                             sn_begin:params[:sn_begin],
							 sn_end:params[:sn_end],
							 random_check_user: params[:random_check_user]})

      respond_to do |format|
        format.xlsx do
          send_data(entry_with_xlsx(@inventories), :type => "application/vnd.openxmlformates-officedocument.spreadsheetml.sheet",
                    :filename => "Inventory_#{DateTime.now.strftime("%Y%m%d%H%M%S")}.xlsx")
        end
        format.html do
          @inventories = @inventories.paginate(page: params[:page])
          # redirect_to inventories_url
        end
      end
    else
      @inventories = @inventories.order(sn: :asc).paginate(page: params[:page])
    end
  end

  def entry_with_xlsx inventories
    p = Axlsx::Package.new
    p.use_shared_strings = true
    wb = p.workbook
    wb.add_worksheet(:name => "sheet1") do |sheet|
      sheet.add_row ["唯一码", "部门", "库位", "零件号", "零件类型", "零件单位","线号","步骤号", "全盘数量", "全盘员工", "全盘时间", "抽盘数量", "抽盘员工", "抽盘时间", "是否抽盘", "iOS新建id"]
      #puts "--testing #{inventories.count}"
      inventories.each_with_index { |inventory, index|
        sheet.add_row [
                          inventory.sn,
                          "\t#{inventory.department}",
                          "\t#{inventory.position}",
                          "\t#{inventory.part_nr}",
                          "\t#{inventory.part_type}",
                          "\t#{inventory.part_unit}",
                          inventory.wire_nr,
                          inventory.process_nr,
                          inventory.check_qty,
                          "\t#{inventory.check_user}",
                          inventory.check_time_display,
                          inventory.random_check_qty,
                          "\t#{inventory.random_check_user}",
                          inventory.random_check_time_display,
                          inventory.is_random_check_display,
                          inventory.ios_created_id
                      ], :types => [:string]
      }
    end
    p.to_stream.read
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_inventory
    @inventory = Inventory.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def inventory_params
    params.require(:inventory).permit(:department, :position, :part_nr,:sn,:part_unit,:part_type,:wire_nr,:process_nr, :check_qty, :check_user, :random_check_qty, :random_check_user, :is_random_check, :ios_created_id, :position_begin, :position_end)
  end
end

web/InventorySystem/app/helpers/inventories_helper.rb
module InventoriesHelper
end

web/InventorySystem/app/views/inventories/_form.html.erb
<%= form_for(@inventory) do |f| %>
    <% if @inventory.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>
          <ul>
            <% @inventory.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="field">
      <%= f.label :sn %><br>
      <%= f.text_field :sn %>
    </div>


    <div class="field">
      <%= f.label :department %><br>
      <%= f.text_field :department %>
    </div>

    <div class="field">
      <%= f.label :position %><br>
      <%= f.text_field :position %>
    </div>
    <div class="field">
      <%= f.label :part_nr %><br>
      <%= f.text_field :part_nr %>
    </div>
    <div class="field">
      <%= f.label :part_unit %><br>
      <%= f.text_field :part_unit %>
    </div>
    <div class="field">
      <%= f.label :part_type %><br>
      <%= f.text_field :part_type %>
    </div>
    <div class="field">
      <%= f.label :wire_nr %><br>
      <%= f.text_field :wire_nr %>
    </div>
    <div class="field">
      <%= f.label :process_nr %><br>
      <%= f.text_field :process_nr %>
    </div>
    <div class="field">
      <%= f.label :check_qty %><br>
      <%= f.text_field :check_qty %>
    </div>
    <div class="field">
      <%= f.label :check_user %><br>
      <%= f.text_field :check_user %>
    </div>

    <div class="field">
      <%= f.label :random_check_qty %><br>
      <%= f.text_field :random_check_qty %>
    </div>
    <div class="field">
      <%= f.label :random_check_user %><br>
      <%= f.text_field :random_check_user %>
    </div>

    <div class="field">
      <%= f.label :is_random_check %><br>
      <%= f.check_box :is_random_check %>
    </div>
    <div class="field">
      <%= f.label :ios_created_id %><br>
      <%= f.text_field :ios_created_id %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, value: '保 存' %>
    </div>
<% end %>

web/InventorySystem/app/views/inventories/edit.html.erb
<h1>Editing Inventory</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

web/InventorySystem/app/views/inventories/import.html.erb
<div id="handle-dialog-modal">
     <div class="handle-dialog-modal-content">
          <p>
               <!--<img src="/assets/loading.gif" />&nbsp;&nbsp;-->
          </p>
     </div>
</div>
<div id="dialog-overlay"></div><p id="notice"><%= notice %></p>
<script type="text/javascript">
    $(function () {
        data_upload("#item-data-uploader", 'xlsx');
    });
</script>
<h1>上传盘点数据</h1>
<hr />
<p>
	<%= link_to '返回', inventories_path, class: 'btn btn-default' %>
	
	<input id="item-data-uploader" type="file" name="files[]" data-url="/inventories/import"/>

    <div class="abstractblock" id="item-data-uploader-preview" style="display:none;"></div>
	
	
</p>

web/InventorySystem/app/views/inventories/index.html.erb
<div id="dialog-overlay"></div><p id="notice"><%= notice %></p>
<script type="text/javascript">
    $(function () {
        data_upload("#item-data-uploader", 'xlsx');
    });
</script>

<style>
    .col-md-12 {
        margin-bottom: 10px;
    }

    .input-group > span {
        min-width: 150px;
    }
</style>

<ol class="breadcrumb">
  <li><span>Inventory System</span></li>
  <li><span>盘点数据管理</span></li>
</ol>
<div class="panel panel-primary">
  <div class="panel-body">
    <%= form_tag inventories_path, :method => 'get' do %>
        <%= hidden_field_tag :search, value=true %>
        <div class="col-md-12">
          <div class="col-md-4">
            <div class="input-group">
              <span class="input-group-addon" id="sizing-addon1">部门：</span>
              <%= text_field_tag :department, params[:department], class: 'form-control' %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="input-group">
              <span class="input-group-addon" id="sizing-addon1">全盘员工号：</span>
              <%= text_field_tag :check_user, params[:check_user], class: 'form-control' %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="input-group">
          <span class="input-group-addon">
            抽盘员工号：
          </span>
              <%= text_field_tag :random_check_user, params[:random_check_user], class: 'form-control' %>
            </div>
          </div>
        </div>

        <div class="col-md-12">
          <div class="col-md-4">
            <div class="input-group">
              <span class="input-group-addon">
                唯一码：
              </span>
              <%= text_field_tag :sn_begin, params[:sn_begin], class: 'form-control' %>
              <%= text_field_tag :sn_end, params[:sn_end], class: 'form-control' %>
            </div>

          </div>
          <div class="col-md-4">
            <div class="input-group">
          <span class="input-group-addon">
            库位号：
          </span>
              <%= text_field_tag :position_begin, params[:position_begin], class: 'form-control' %>
              <%= text_field_tag :position_end, params[:position_end], class: 'form-control' %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="input-group">
          <span class="input-group-addon">
            零件号：
          </span>
              <%= text_field_tag :part_nr, params[:part_nr], class: 'form-control' %>
            </div>

            <div class="input-group">
          <span class="input-group-addon">
            是否是iOS新建：
          </span>
              <%= select_tag :ios_created_id, options_for_select([["否", 0], ["是", 1]], params[:ios_created_id]), {prompt: '选择', class: 'form-control'} %>
            </div>
          </div>
        </div>
        <div class="col-md-12">
          <div class="col-md-4">
            <div class="input-group">
          <span class="input-group-addon">
          是否是抽盘：
        </span>
              <%= select_tag :is_random_check, options_for_select([["否", 0], ["是", 1]], params[:is_random_check]), {prompt: '选择', class: 'form-control'} %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="input-group"><span class="input-group-addon">
          显示方式:
        </span>
              <%= select_tag :format, options_for_select([["Web", "html"], ["Excel File(MS 07 or later)", "xlsx"]], "html"), class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-4">
            <%= submit_tag "查询", :name => nil, class: 'btn btn-primary', style: 'width:200px;' %>
          </div>
        </div>
    <% end %>
    <div class="col-md-12">
      <div class="btn-group" style="margin-left: 15px;">
        <%= link_to '创建盘点数据', new_inventory_path, class: 'btn btn-default' %>
        <a name="down_template" href="/files/download?folder=inventory&file=inventory_template.xlsx" class='btn btn-default'>下载模版</a>
        <!--	<input id="item-data-uploader" type="file" name="files[]" data-url="/inventories/import"/>
            <div class="abstractblock" id="item-data-uploader-preview" style="display:none;"></div>-->
        <%= link_to '上传数据', import_inventories_path, class: 'btn btn-info' %>
        <%= link_to '盘点统计', root_path, class: 'btn btn-warning' %>
        <%= link_to '生成抽盘数据', random_inventories_path, remote: true, :data => {confirm: "抽盘数据将被还原到初始化，确定生成？", :"disable-with" => "生成中，请稍等..."}, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

<%= will_paginate @inventories, renderer: BootstrapPagination::Rails %>

<div class="page_info">
  <%= page_entries_info @inventories %>
</div>

<table class="table table-striped table-hover table-bordered" id="editable-sample">
  <thead>
  <tr>
    <th></th>
    <th>唯一码</th>
    <th>部门</th>
    <th>库位</th>
    <th>零件号</th>
    <th>零件类型</th>
    <th>零件单位</th>
    <th>线号</th>
    <th>步骤号</th>
    <th>全盘数量</th>
    <th>全盘员工</th>
    <th>全盘时间</th>
    <th>抽盘数量</th>
    <th>抽盘员工</th>
    <th>抽盘时间</th>
    <th>是否抽盘</th>
    <th>iOS新建id</th>
    <th colspan="3">管理</th>
  </tr>
  </thead>

  <tbody>
  <% @inventories.each_with_index do |inventory, index| %>
      <tr>
        <td style="background-color: lightgray;"><%= index+1 %></td>
        <td><%= inventory.sn %></td>
        <td><%= inventory.department %></td>
        <td><%= inventory.position %></td>
        <td><%= inventory.part_nr %></td>
        <td><%= inventory.part_type %></td>
        <td><%= inventory.part_unit %></td>
        <td><%= inventory.wire_nr %></td>
        <td><%= inventory.process_nr %></td>
        <td><%= inventory.check_qty %></td>
        <td><%= inventory.check_user %></td>
        <td><%= inventory.check_time_display %></td>
        <td><%= inventory.random_check_qty %></td>
        <td><%= inventory.random_check_user %></td>
        <td><%= inventory.random_check_time_display %></td>
        <td><%= inventory.is_random_check_display %></td>
        <td><%= inventory.ios_created_id %></td>
        <td><%= link_to '详情', inventory %></td>
        <td><%= link_to '编辑', edit_inventory_path(inventory) %></td>
        <td><%= link_to '删除', inventory, method: :delete, data: {confirm: '是否删除该条记录?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="pull-right">
  <%= will_paginate @inventories, renderer: BootstrapPagination::Rails %>
</div>
<br>
<div>
  <h4>说明：</h4>

  <div>
    <p><strong>零件类型</strong>：不可空，为<%= Inventory::PART_TYPES.join(',') %></p>
  </div>
</div>

web/InventorySystem/app/views/inventories/new.html.erb
<h1>创建库存</h1>

<%= render 'form' %>

<%= link_to 'Back', inventories_path %>

web/InventorySystem/app/views/inventories/random.js.erb
alert("生成抽盘数据成功");
window.location.reload();

web/InventorySystem/app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Department:</strong>
  <%= @inventory.department %>
</p>

<p>
  <strong>Position:</strong>
  <%= @inventory.position %>
</p>

<p>
  <strong>Part Nr:</strong>
  <%= @inventory.part_nr %>
</p>
<p>
  <strong>Part Unit:</strong>
  <%= @inventory.part_unit %>
</p>
<p>
  <strong>Part Type:</strong>
  <%= @inventory.part_type %>
</p>
<p>
  <strong>Wire Nr:</strong>
  <%= @inventory.wire_nr %>
</p>
<p>
  <strong>Process Nr:</strong>
  <%= @inventory.process_nr %>
</p>


<p>
  <strong>Check qty:</strong>
  <%= @inventory.check_qty %>
</p>

<p>
  <strong>Check user:</strong>
  <%= @inventory.check_user %>
</p>

<p>
  <strong>Check time:</strong>
  <%= @inventory.check_time %>
</p>

<p>
  <strong>Random check qty:</strong>
  <%= @inventory.random_check_qty %>
</p>

<p>
  <strong>Random check user:</strong>
  <%= @inventory.random_check_user %>
</p>

<p>
  <strong>Random check time:</strong>
  <%= @inventory.random_check_time %>
</p>

<p>
  <strong>Is random check:</strong>
  <%= @inventory.is_random_check %>
</p>

<p>
  <strong>Ios created:</strong>
  <%= @inventory.ios_created_id %>
</p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>