web/InventorySystem/config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :file_tasks do
    member do
      get :manual_update
    end

    collection do
      get :search
    end
  end
  resources :inventory_files
  resources :settings
  resources :parts do
    collection do
      match :import, action: :import, via: [:get, :post]
      get :search
    end
  end

  get 'dashboard/index'

  get 'dashboard/setting'

  post 'dashboard/setting'

  root to: 'dashboard#index'

  resources :inventories do
    collection do
      match :import, action: :import, via: [:get, :post]
      get :search
      get :random
    end
  end

  resources :files do
    collection do
      get :download
    end
  end

  resources :users do
    collection do
      match :import, action: :import, via: [:get, :post]
      get :search
    end
  end

  mount ApplicationAPI => '/api'
end

web/InventorySystem/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  nr         :string(255)
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  validates :name, :nr, :role, presence: true
  validates_uniqueness_of :nr
  before_save :set_default_value

  self.per_page = 100

  ROLES=%w(盘点员 组长 其他)

  def self.auth nr
    user = User.find_by_nr(nr)
    user
  end

  def self.search(search)
    if search
      where("name LIKE ? or nr Like ? or role like ?", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      find(:all)
    end
  end

  def self.validate_role(role)
    ROLES.include? role
  end

  def id_span_count
    spans=self.id_span.split(',')
    count=0
    spans.each do |span|
      sspans=span.split('-')
      count+=(sspans[1].to_i-sspans[0].to_i+1)
    end

    count
  end

  def set_default_value

    if self.id_span.blank?
      self.id_span=''
    end

  end
end

web/InventorySystem/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User
    @users = @users.search(params[:search]) if params[:search]
    @users = @users.paginate(page: params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    if request.post?
      msg = Message.new
      tmp_file_path = 'uploadfiles'

      begin
        file = params[:files][0]
        fd = FileData.new(data: file, oriName: file.original_filename, path: tmp_file_path, pathName: "#{Time.now.strftime('%Y%m%d%H%M%S%L')}~#{file.original_filename}")
        fd.save
        msg = Excel::UserService.import(fd)
      rescue => e
        msg.content = e.message
      end
      render json: msg
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nr, :name,:role,:id_span)
    end
end

web/InventorySystem/app/helpers/users_helper.rb
module UsersHelper
  def role_select_options
    User::ROLES.map { |v| [v, v] }
  end
end

web/InventorySystem/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :nr %><br>
      <%= f.text_field :nr %>
    </div>
    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :role %><br>
      <%= f.select :role, role_select_options %>
    </div>
    <div class="form-group">
      <%= f.label :id_span %><br>
      <%= f.text_field :id_span %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

web/InventorySystem/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

web/InventorySystem/app/views/users/import.html.erb
<div id="handle-dialog-modal">
     <div class="handle-dialog-modal-content">
          <p>
               <!--<img src="/assets/loading.gif" />&nbsp;&nbsp;-->
          </p>
     </div>
</div>
<div id="dialog-overlay"></div><p id="notice"><%= notice %></p>
<script type="text/javascript">
    $(function () {
        data_upload("#item-data-uploader", 'xlsx');
    });
</script>
<h1>上传用户</h1>
<hr />
<p>
	<a name="down_template" href="/files/download?folder=inventory&file=user_template.xlsx" class='btn btn-default' >下载模版</a>
	<%= link_to '返回', users_path, class: 'btn btn-default' %>
	
	<input id="item-data-uploader" type="file" name="files[]" data-url="/users/import"/>

    <div class="abstractblock" id="item-data-uploader-preview" style="display:none;"></div>
	
	
</p>

web/InventorySystem/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<ol class="breadcrumb">
  <li><span>Inventory System</span></li>
  <li><span>员工基础信息</span></li>
</ol>

<div class="alert alert-danger" role="alert">
  <p><strong>权限说明</strong>：盘点员、组长、其他，'其他'代表非重点控制的权限</p>

  <p><strong>任务ID说明</strong>：任务ID是一个范围多范围使用英文逗号隔开，如2-2,3-100,则其任务量为1+98=99个 </p>
</div>

<div class="panel panel-primary">
  <div class="panel-body">
    <div class="row" style="height: 40px;">
      <div class="col-md-offset-1 col-md-4">
        <%= form_tag users_path, :method => 'get' do %>
            <div class="input-group">
              <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: '员工号、 姓名、 权限' %>
              <span class="input-group-btn">
             <%= submit_tag "查询", :name => nil, class: 'btn btn-default', style: 'width:150px;' %>
            </span>
            </div>
        <% end %>
      </div>
      <div class="col-md-offset-1 col-md-2">
        <%= link_to '创建员工', new_user_path, class: 'btn btn-default' %>
      </div>
      <div class="col-md-2">
        <a name="down_template" href="/files/download?folder=inventory&file=user_template.xlsx" class='btn btn-default'>下载模版</a>
      </div>
      <div class="col-md-2">
        <%= link_to '上传数据', import_users_path, class: 'btn btn-primary', style: 'color:white;' %>
      </div>
    </div>
  </div>
</div>

<div class="pull-right">
  <div class="page_info">
    <%= page_entries_info @users %>
  </div>
  <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
</div>
<table class="table table-striped table-hover table-bordered" id="editable-sample">
  <thead>
  <tr>
    <th width="150px;">序号</th>
    <th>员工号</th>
    <th>姓名</th>
    <th>权限</th>
    <th>任务ID</th>
    <th>任务量</th>
    <th>管理</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each_with_index do |user, index| %>
      <tr class="">
        <td><%= index+1 %></td>
        <td><%= user.nr %></td>
        <td><%= user.name %></td>
        <td><%= user.role %></td>
        <td><%= user.id_span %></td>
        <td><%= user.id_span_count %></td>
        <td>
          <%= link_to '编辑', edit_user_path(user) %>

          <%= link_to '删除', user_path(user), method: 'delete', data: {confirm: '确定删除吗?'} %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<div class="pull-right">
  <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
</div>
<br>

web/InventorySystem/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

web/InventorySystem/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nr:</strong>
  <%= @user.nr %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>
<p>
  <strong>任务ID:</strong>
  <%= @user.id_span %>
</p>
<p>
  <strong>任务量:</strong>
  <%= @user.id_span_count %>
</p>

<%= link_to '编辑', edit_user_path(@user) %> |
<%= link_to '返回', users_path %>