web/InventorySystem/config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :file_tasks do
    member do
      get :manual_update
    end

    collection do
      get :search
    end
  end
  resources :inventory_files
  resources :settings
  resources :parts do
    collection do
      match :import, action: :import, via: [:get, :post]
      get :search
    end
  end

  get 'dashboard/index'

  get 'dashboard/setting'

  post 'dashboard/setting'

  root to: 'dashboard#index'

  resources :inventories do
    collection do
      match :import, action: :import, via: [:get, :post]
      get :search
      get :random
    end
  end

  resources :files do
    collection do
      get :download
    end
  end

  resources :users do
    collection do
      match :import, action: :import, via: [:get, :post]
      get :search
    end
  end

  mount ApplicationAPI => '/api'
end

web/InventorySystem/app/models/part.rb
class Part < ActiveRecord::Base
  self.inheritance_column=:_type_disabled
  validates :nr, presence: true, uniqueness: {message: '零件号必须唯一'}
  validates :unit, presence: {message: '单位不可空'}
  validates :type, presence: {message: '类型不可空'}

  # has_many :inventories, foreign_key: :part_nr, primary_key: :nr

  self.per_page = 50

  scoped_search on: [:nr, :unit, :type]

  def nr_prefix
    "#{Setting.part_prefix}#{self.nr}"
  end
end

web/InventorySystem/app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    if params[:search]
      @parts= params[:q].blank? ? Part.all : Part.search_for(params[:q])

      respond_to do |format|
        format.xlsx do
          send_data(entry_with_xlsx(@parts), :type => "application/vnd.openxmlformates-officedocument.spreadsheetml.sheet",
                    :filename => "Part_#{DateTime.now.strftime("%Y%m%d%H%M%S")}.xlsx")
        end
        format.html do
          @parts = @parts.paginate(page: params[:page])
        end
      end
    else
      @parts = Part.paginate(page: params[:page])
    end
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: 'Part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def import
    if request.post?
      msg = Message.new
      tmp_file_path = 'uploadfiles'

      begin
        file = params[:files][0]
        fd = FileData.new(data: file, oriName: file.original_filename, path: tmp_file_path, pathName: "#{Time.now.strftime('%Y%m%d%H%M%S%L')}~#{file.original_filename}")
        fd.save
        msg = Excel::PartService.import(fd)
      rescue => e
        msg.content = e.message
      end
      render json: msg
    end
  end

  def entry_with_xlsx parts
    p = Axlsx::Package.new
    p.use_shared_strings = true
    wb = p.workbook
    wb.add_worksheet(:name => "sheet1") do |sheet|
      sheet.add_row ["零件号", "类型", "单位"]
      #puts "--testing #{inventories.count}"
      parts.each { |part|
        sheet.add_row [
                          part.nr,
                          part.type,
                          part.unit
                      ], :types => [:string]
      }
    end
    p.to_stream.read
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_part
    @part = Part.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def part_params
    params.require(:part).permit(:nr, :type, :unit)
  end
end

web/InventorySystem/app/helpers/parts_helper.rb
module PartsHelper
end

web/InventorySystem/app/views/parts/_form.html.erb
<%= simple_form_for(@part) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nr %>
    <%= f.input :type %>
    <%= f.input :unit %>
  </div>

    <div class="form-actions">
      <%= f.button :submit, value: '保 存' %>
    </div>
<% end %>

web/InventorySystem/app/views/parts/edit.html.erb
<h1>Editing Part</h1>

<%= render 'form' %>

<%= link_to 'Show', @part %> |
<%= link_to 'Back', parts_path %>

web/InventorySystem/app/views/parts/import.html.erb
<div id="handle-dialog-modal">
     <div class="handle-dialog-modal-content">
          <p>
               <!--<img src="/assets/loading.gif" />&nbsp;&nbsp;-->
          </p>
     </div>
</div>
<div id="dialog-overlay"></div><p id="notice"><%= notice %></p>
<script type="text/javascript">
    $(function () {
        data_upload("#item-data-uploader", 'xlsx');
    });
</script>
<h1>上传零件</h1>
<hr />
<p>
	<a name="down_template" href="/files/download?folder=inventory&file=part_template.xlsx" class='btn btn-default' >下载模版</a>
	<%= link_to '返回', parts_path, class: 'btn btn-default' %>
	
	<input id="item-data-uploader" type="file" name="files[]" data-url="/parts/import"/>

    <div class="abstractblock" id="item-data-uploader-preview" style="display:none;"></div>
	
	
</p>

web/InventorySystem/app/views/parts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>零件基础信息</h1>
<div>
  <%= form_tag parts_path, :method => 'get' do %>
      <p>
        <%= hidden_field_tag :search, value=true %>
        输入(零件号\类型\单位)：<%= text_field_tag :q, params[:q] %>
        显示方式:
        <%= select_tag :format, options_for_select([["Web", "html"], ["Excel File(MS 07 or later)", "xlsx"]], "html") %>
        <%= submit_tag "查询", :name => nil, class: 'btn btn-primary' %>
      </p>
  <% end %>
</div>

<div class="btn-group">
  <%= link_to '创建零件库', new_part_path, class: 'btn btn-default' %>
  <a name="down_template" href="/files/download?folder=inventory&file=part_template.xlsx" class='btn btn-default'>下载模版</a>

  <div class="abstractblock" id="item-data-uploader-preview" style="display:none;"></div>
  <%= link_to '上传数据', import_parts_path, class: 'btn btn-primary' %>

</div>
<div class="btn-group pull-right">

  <div class="page_info">
    <%= page_entries_info @parts %>
  </div>
  <%= will_paginate @parts, renderer: BootstrapPagination::Rails %>
</div>
<table class="table table-striped table-hover table-bordered" id="editable-sample">
  <thead>
  <tr>
    <th>零件号</th>
    <th>零件扫描号</th>
    <th>类型</th>
    <th>单位</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
  <% @parts.each do |part| %>
      <tr>
        <td><%= part.nr %></td>
        <td><%= part.nr_prefix %></td>
        <td><%= part.type %></td>
        <td><%= part.unit %></td>
        <td><%= link_to '编辑', edit_part_path(part) %></td>
        <td><%= link_to '删除', part, method: :delete, data: {confirm: '确定?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<div class="pull-right">
  <%= will_paginate @parts, renderer: BootstrapPagination::Rails %>
</div>

<script type="text/javascript">
    $(function () {
        data_upload("#item-data-uploader", 'xlsx');
    });
</script>

web/InventorySystem/app/views/parts/new.html.erb
<h1>New Part</h1>

<%= render 'form' %>

<%= link_to 'Back', parts_path %>

web/InventorySystem/app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nr:</strong>
  <%= @part.nr %>
</p>

<p>
  <strong>Type:</strong>
  <%= @part.type %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @part.unit %>
</p>

<%= link_to 'Edit', edit_part_path(@part) %> |
<%= link_to 'Back', parts_path %>